/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownInputParams; } | { pathname: `/entry/edit`; params?: Router.UnknownInputParams; } | { pathname: `/entry/new`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-vault`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/unlock`; params?: Router.UnknownInputParams; } | { pathname: `/entry/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/new`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/create-vault`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/unlock`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vault${`?${string}` | `#${string}` | ''}` | `/vault${`?${string}` | `#${string}` | ''}` | `/entry/edit${`?${string}` | `#${string}` | ''}` | `/entry/new${`?${string}` | `#${string}` | ''}` | `/onboarding/create-vault${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/unlock${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vault` | `/vault`; params?: Router.UnknownInputParams; } | { pathname: `/entry/edit`; params?: Router.UnknownInputParams; } | { pathname: `/entry/new`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-vault`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/unlock`; params?: Router.UnknownInputParams; } | `/entry/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/entry/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
